---
title: "Feature2"
author: "Yingxin Zhang (yz3032)"
date: "3/21/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("EBImage")
library(stringr)
```

```{r}
img_dir <- "C://training_data/raw_images"
n_files <- length(list.files(img_dir))
time_feature_base <- 769
save(time_feature_base, file = "C://Users/Lloyd/Documents/GitHub/spr2017-proj3-group-2/output/time_feature_base.rData")
```

```{r}
###method 1 : resize+threshold
###build a new folder named newraw_images
ptm <- proc.time()
for(i in 1:n_files){
  ii <- str_pad(i, 4, pad = "0")
  img <- readImage(paste0(img_dir, "/","image_", ii,".jpg"))
  img1 <- resize(img,512,512)
  img2 <- thresh(img1, w=60, h=60, offset=0.06)
  writeImage(img2,file = paste0("C://training_data/newraw_images/", "image_",ii,".jpg"))
}
time <- proc.time() - ptm
time_feature_resize_adaptive <- 769 + time[[3]]
save(time_feature_resize_adaptive, file = "C://Users/Lloyd/Documents/GitHub/spr2017-proj3-group-2/output/time_feature_resize+adaptive.rData")
```

```{r}
###method2 : resize
###build a new folder named newraw_images1
ptm <- proc.time()
for(i in 1:n_files){
  ii <- str_pad(i, 4, pad = "0")
  img <- readImage(paste0(img_dir, "/","image_", ii,".jpg"))
  img1 <- resize(img,512,512)
  #img2 <- thresh(img1, w=60, h=60, offset=0.06)
  writeImage(img1,file = paste0("C://training_data/newraw_images1/", "image_",ii,".jpg"))
}
time <- proc.time() - ptm
time_feature_resize <- 769 + time[[3]]
save(time_feature_resize, file = "C://Users/Lloyd/Documents/GitHub/spr2017-proj3-group-2/output/time_feature_resize.rData")
```

```{r}
###method3: threshold
###build a new folder named newraw_images2
ptm <- proc.time()
for(i in 1:n_files){
  ii <- str_pad(i, 4, pad = "0")
  img <- readImage(paste0(img_dir, "/","image_", ii,".jpg"))
  #img1 <- resize(img,512,512)
  img2 <- thresh(img, w=60, h=60, offset=0.06)
  writeImage(img2,file = paste0("C://training_data/newraw_images2/", "image_",ii,".jpg"))
}
time <- proc.time() - ptm
time_feature_adaptive <- 769 + time[[3]]
save(time_feature_adaptive, file = "C://Users/Lloyd/Documents/GitHub/spr2017-proj3-group-2/output/time_feature_adaptive.rData")
```

